"""initial_migration

Revision ID: de15ef4dec68
Revises: 
Create Date: 2026-01-09 13:44:15.863751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de15ef4dec68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notificacoes', 'tipo')
    op.drop_column('notificacoes', 'canal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notificacoes', sa.Column('canal', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('notificacoes', sa.Column('tipo', sa.VARCHAR(length=17), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
